### ISSUE TITLE
Don't upload `build` and `.dart_tool` to git

### ISSUE THREAD

**Issue by ZiyadF296** [AryamanGurjar/true-false-quiz-app-flutter#1]
I took a quick look over this repo and it seems you have uploaded the build folder and some others. The folder shouldn't be uploaded and when developers clone it, they can generate it.

Please include the `build` and `.dart_tool` directory path in the gitignore file.

**Comment by AryamanGurjar** [comment]
ooh now I got why it is not showing 90%+ dart 
Thank you so much for telling me this 😄
